# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_auto_20160422_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='taggeditem',
            options={'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', '-timestamp'], 'verbose_name_plural': 'Videos'},
        ),
    ]
