# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_auto_20160427_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 27, 15, 9, 11, 326871, tzinfo=utc), verbose_name=b'End Date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 27, 15, 9, 11, 326715, tzinfo=utc), verbose_name=b'Start Date'),
        ),
    ]
