# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_auto_20160427_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 30, 15, 38, 6, 953108, tzinfo=utc), verbose_name=b'End Date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 30, 15, 38, 6, 953041, tzinfo=utc), verbose_name=b'Start Date'),
        ),
    ]
