# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_auto_20160502_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 11, 36, 37, 982493, tzinfo=utc), verbose_name=b'End Date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 11, 36, 37, 982388, tzinfo=utc), verbose_name=b'Start Date'),
        ),
    ]
