# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_auto_20160502_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 16, 17, 14, 853299, tzinfo=utc), verbose_name=b'End Date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 16, 17, 14, 853195, tzinfo=utc), verbose_name=b'Start Date'),
        ),
        migrations.AlterField(
            model_name='transactionpayu',
            name='amount',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpayu',
            name='customer_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
