# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_auto_20160502_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 4, 8, 33, 15, 966439, tzinfo=utc), verbose_name=b'End Date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 4, 8, 33, 15, 966379, tzinfo=utc), verbose_name=b'Start Date'),
        ),
    ]
