# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_auto_20160511_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'End Date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Start Date'),
        ),
    ]
