# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0029_auto_20160425_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 27, 14, 14, 19, 807855, tzinfo=utc)),
        ),
    ]
