# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0030_auto_20160427_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 27, 14, 23, 57, 315349, tzinfo=utc)),
        ),
    ]
