# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0033_auto_20160427_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 30, 15, 38, 7, 62670, tzinfo=utc)),
        ),
    ]
