# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0036_auto_20160502_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 11, 36, 54, 198716, tzinfo=utc)),
        ),
    ]
