# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0039_auto_20160502_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 12, 10, 46, 410307, tzinfo=utc)),
        ),
    ]
