# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0040_auto_20160502_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 16, 17, 14, 882930, tzinfo=utc)),
        ),
    ]
