# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0041_auto_20160502_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 4, 8, 33, 15, 989149, tzinfo=utc)),
        ),
    ]
