# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0043_auto_20160504_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 11, 13, 9, 22, 38646, tzinfo=utc)),
        ),
    ]
