# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0045_auto_20160517_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'PageViews'},
        ),
    ]
